# Generated by Django 5.1.7 on 2025-04-17 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0002_alter_cv_options_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertatrabajo',
            name='creada_por_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionOfertas.personanatural'),
        ),
        migrations.AlterField(
            model_name='ofertatrabajo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionOfertas.empresa'),
        ),
    ]
