# Generated by Django 5.1.7 on 2025-04-18 00:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestionOfertas', '0003_ofertatrabajo_creada_por_persona_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ofertatrabajo',
            name='gestionOfer_empresa_7fd74b_idx',
        ),
        migrations.RemoveField(
            model_name='ofertatrabajo',
            name='creada_por_persona',
        ),
        migrations.RemoveField(
            model_name='ofertatrabajo',
            name='empresa',
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de creador'),
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del creador'),
        ),
        migrations.AlterField(
            model_name='ofertatrabajo',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 4, 17), verbose_name='Fecha de publicación'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='ofertatrabajo',
            index=models.Index(fields=['content_type', 'object_id'], name='gestionOfer_content_2fb7c4_idx'),
        ),
    ]
