# Generated by Django 5.2 on 2025-04-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0003_valoracion_alter_cv_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personanatural',
            name='direccion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
