# Generated by Django 5.2 on 2025-04-20 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0004_remove_ofertatrabajo_gestionofer_empresa_7fd74b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertatrabajo',
            name='usuario_creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
