# Generated by Django 5.1.7 on 2025-04-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0005_alter_ofertatrabajo_options_ofertatrabajo_destacada_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ofertatrabajo',
            name='gestionOfer_nombre_d337d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='ofertatrabajo',
            name='gestionOfer_categor_b8af3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='ofertatrabajo',
            name='gestionOfer_creador_949159_idx',
        ),
        migrations.RemoveIndex(
            model_name='ofertatrabajo',
            name='gestionOfer_empresa_7fd74b_idx',
        ),
        migrations.RemoveIndex(
            model_name='ofertatrabajo',
            name='gestionOfer_esta_ac_8d6d79_idx',
        ),
    ]
