# Generated by Django 5.2 on 2025-04-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0005_ofertatrabajo_usuario_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertatrabajo',
            name='usuario_creador',
        ),
    ]
