# Generated by Django 5.1.7 on 2025-04-23 23:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0006_remove_ofertatrabajo_gestionofer_nombre_d337d8_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertatrabajo',
            options={'ordering': ['-fecha_publicacion'], 'permissions': [('destacar_oferta', 'Puede destacar ofertas')], 'verbose_name': 'Oferta de trabajo', 'verbose_name_plural': 'Ofertas de trabajo'},
        ),
        migrations.RemoveField(
            model_name='ofertatrabajo',
            name='destacada',
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='es_servicio',
            field=models.BooleanField(default=False, verbose_name='Es servicio'),
        ),
        migrations.AlterField(
            model_name='ofertatrabajo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='ofertatrabajo',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ofertatrabajo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas_publicadas', to='gestionOfertas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='ofertatrabajo',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Cierre'),
        ),
        migrations.AlterField(
            model_name='ofertatrabajo',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicación'),
        ),
        migrations.AlterField(
            model_name='ofertatrabajo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
