# Generated by Django 5.1.7 on 2025-05-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0008_postulacion_filtrada_alter_cv_archivo_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertatrabajo',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='modo_urgente',
            field=models.BooleanField(default=False),
        ),
    ]
