# Generated by Django 5.1.7 on 2025-05-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0009_ofertatrabajo_urgente_personanatural_modo_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='personanatural',
            name='recibir_ofertas_urgentes',
            field=models.BooleanField(default=False, verbose_name='Recibir ofertas urgentes por correo'),
        ),
    ]
