# Generated by Django 5.1.7 on 2025-05-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0010_personanatural_recibir_ofertas_urgentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertatrabajo',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofertatrabajo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
