# Generated by Django 5.1.7 on 2025-05-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0011_remove_ofertatrabajo_ubicacion_ofertatrabajo_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertatrabajo',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
    ]
