# Generated by Django 5.2 on 2025-06-04 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0012_ofertatrabajo_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experiencia_resumen',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cv',
            name='datos_analizados_ia',
            field=models.JSONField(blank=True, help_text='JSON completo de la información extraída del CV por la IA.', null=True, verbose_name='Datos analizados por IA'),
        ),
        migrations.AddField(
            model_name='cv',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de contacto'),
        ),
        migrations.AddField(
            model_name='cv',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo del CV'),
        ),
        migrations.AddField(
            model_name='cv',
            name='resumen_profesional',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen profesional'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 6, 4, 21, 7, 35, 665591, tzinfo=datetime.timezone.utc), verbose_name='Fecha de actualización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 4, 21, 8, 1, 764488, tzinfo=datetime.timezone.utc), verbose_name='Fecha de subida'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExperienciaLaboral',
        ),
    ]
