# Generated by Django 5.2 on 2025-06-02 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0012_ofertatrabajo_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='muestras_trabajo/')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
