# Generated by Django 5.2 on 2025-06-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0013_muestratrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='fecha_contratacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de contratación'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['fecha_contratacion'], name='gestionOfer_fecha_c_1c8749_idx'),
        ),
    ]
