# Generated by Django 5.2 on 2025-06-11 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0015_remove_cv_correo_remove_cv_experiencia_resumen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificadoantecedentes',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Certificado de Antecedentes', 'verbose_name_plural': 'Certificados de Antecedentes'},
        ),
        migrations.RemoveIndex(
            model_name='certificadoantecedentes',
            name='gestionOfer_usuario_4fa1f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='certificadoantecedentes',
            name='gestionOfer_esta_vi_5a15a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='certificadoantecedentes',
            name='gestionOfer_tiene_a_856846_idx',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='archivo_pdf',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='esta_vigente',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='fecha_carga',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='fecha_nacimiento_certificado',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='nombre_completo_certificado',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='rut_certificado',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='tiene_antecedentes_penales',
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='certificado_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del Certificado en Cloud Storage'),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='datos_extraidos',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos del Certificado extraídos por IA'),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='esta_verificado',
            field=models.BooleanField(default=False, verbose_name='Certificado Verificado (por el sistema o manualmente)'),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificadoantecedentes',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado_antecedentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
