# Generated by Django 5.2 on 2025-06-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0016_alter_certificadoantecedentes_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificadoAntecedentes',
        ),
    ]
