# Generated by Django 5.2 on 2025-06-11 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0017_delete_certificadoantecedentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoAntecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del Certificado en Cloud Storage')),
                ('datos_extraidos', models.JSONField(blank=True, null=True, verbose_name='Datos del Certificado extraídos por IA')),
                ('esta_verificado', models.BooleanField(default=False, verbose_name='Certificado Verificado (por el sistema o manualmente)')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado_antecedentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado de Antecedentes',
                'verbose_name_plural': 'Certificados de Antecedentes',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
