# Generated by Django 5.2 on 2025-06-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0018_certificadoantecedentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoantecedentes',
            name='datos_extraidos',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Datos del Certificado extraídos por IA'),
        ),
    ]
