# Generated by Django 5.2 on 2025-06-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0019_alter_certificadoantecedentes_datos_extraidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='usuario',
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificado_antecedentes', to='gestionOfertas.personanatural'),
            preserve_default=False,
        ),
    ]
