# Generated by Django 5.2 on 2025-06-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0020_remove_certificadoantecedentes_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='certificado_url',
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='certificado_archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
