# Generated by Django 5.2 on 2025-06-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0021_remove_certificadoantecedentes_certificado_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='esta_verificado',
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='estado_verificacion',
            field=models.CharField(choices=[('PENDIENTE', 'En Verificación'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', help_text='Estado actual de la verificación y análisis del Certificado de Antecedentes.', max_length=20, verbose_name='Estado de Verificación'),
        ),
        migrations.AddField(
            model_name='cv',
            name='estado_verificacion',
            field=models.CharField(choices=[('PENDIENTE', 'En Verificación'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', help_text='Estado actual de la verificación y análisis del CV.', max_length=20, verbose_name='Estado de Verificación'),
        ),
    ]
