# Generated by Django 5.2 on 2025-06-15 01:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0022_remove_certificadoantecedentes_esta_verificado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificadoantecedentes',
            options={'ordering': ['-last_processed_at'], 'verbose_name': 'Certificado de Antecedentes', 'verbose_name_plural': 'Certificados de Antecedentes'},
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={},
        ),
        migrations.RenameField(
            model_name='certificadoantecedentes',
            old_name='fecha_actualizacion',
            new_name='last_processed_at',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='certificado_archivo',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='datos_extraidos',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='estado_verificacion',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='fecha_subida',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='estado_verificacion',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='fecha_subida',
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='archivo_certificado',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='datos_analizados_ia',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='institucion_emisora',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='nombre_completo_certificado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pendiente de Procesamiento'), ('processing', 'Procesando por IA'), ('processed', 'Procesado Exitosamente'), ('rejected', 'Rechazado por IA'), ('error', 'Error en Procesamiento')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='rut_certificado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='certificadoantecedentes',
            name='tiene_anotaciones_vigentes',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='last_processed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pendiente de Procesamiento'), ('processing', 'Procesando por IA'), ('processed', 'Procesado Exitosamente'), ('rejected', 'Rechazado por IA'), ('error', 'Error en Procesamiento')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='archivo_cv',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='datos_analizados_ia',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='cv',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='resumen_profesional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
