# Generated by Django 5.2 on 2025-06-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0023_alter_certificadoantecedentes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='institucion_emisora',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='nombre_completo_certificado',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='rut_certificado',
        ),
        migrations.RemoveField(
            model_name='certificadoantecedentes',
            name='tiene_anotaciones_vigentes',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='email_contacto',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='resumen_profesional',
        ),
    ]
