# Generated by Django 5.2 on 2025-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0024_remove_certificadoantecedentes_fecha_emision_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='postulacion',
            name='gestionOfer_filtrad_3de3aa_idx',
        ),
        migrations.RemoveField(
            model_name='postulacion',
            name='filtrada',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='IA_match_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje de compatibilidad calculado por la IA (0.00 a 100.00)', max_digits=5, null=True, verbose_name='Puntaje de Match IA'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='estado_ia_match',
            field=models.CharField(choices=[('ia_pendiente', 'IA Pendiente'), ('ia_aprobado', 'IA Aprobado'), ('ia_rechazado', 'IA Rechazado'), ('ia_error', 'Error IA')], default='ia_pendiente', help_text='Resultado del análisis de compatibilidad realizado por la Inteligencia Artificial.', max_length=20, verbose_name='Estado Match IA'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('ia_en_proceso', 'IA en proceso'), ('pendiente', 'Pendiente'), ('match', 'Match'), ('contratado', 'Contratado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='ia_en_proceso', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['estado_ia_match'], name='gestionOfer_estado__1d412b_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['IA_match_score'], name='gestionOfer_IA_matc_ac77ac_idx'),
        ),
    ]
