# Generated by Django 5.2 on 2025-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0025_remove_postulacion_gestionofer_filtrad_3de3aa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
