# Generated by Django 5.2 on 2025-06-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0026_usuario_latitud_usuario_longitud'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='postulacion',
            name='gestionOfer_estado__1d412b_idx',
        ),
        migrations.RemoveIndex(
            model_name='postulacion',
            name='gestionOfer_IA_matc_ac77ac_idx',
        ),
        migrations.RemoveField(
            model_name='postulacion',
            name='IA_match_score',
        ),
        migrations.RemoveField(
            model_name='postulacion',
            name='estado_ia_match',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='filtrada',
            field=models.BooleanField(default=False, help_text='Indica si la postulación ha sido filtrada manualmente', verbose_name='Filtrada'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('filtrado', 'Filtrado'), ('match', 'Match'), ('contratado', 'Contratado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['filtrada'], name='gestionOfer_filtrad_3de3aa_idx'),
        ),
    ]
