# Generated by Django 5.2 on 2025-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0027_remove_postulacion_gestionofer_estado__1d412b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoantecedentes',
            name='archivo_certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='archivo_cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
