# Generated by Django 5.2 on 2025-06-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOfertas', '0029_alter_usuario_latitud_alter_usuario_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='estado_ia_analisis',
            field=models.CharField(choices=[('en_analisis', 'En Análisis'), ('aprobado_ia', 'Aprobado por IA'), ('rechazado_ia', 'Rechazado por IA'), ('error_analisis', 'Error de Análisis'), ('pendiente_ia', 'Pendiente de Análisis IA')], default='pendiente_ia', help_text='Estado del procesamiento del análisis de idoneidad por IA.', max_length=20, verbose_name='Estado de Análisis IA'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='puntaje_ia',
            field=models.IntegerField(blank=True, help_text='Puntaje de 0-100 calculado por la IA.', null=True, verbose_name='Puntaje de Idoneidad IA'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='razon_estado_ia',
            field=models.TextField(blank=True, help_text='Detalles sobre el estado del análisis de la IA (rechazo, error).', verbose_name='Razón del Estado IA'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='razones_ia',
            field=models.JSONField(blank=True, default=dict, help_text='Detalles del análisis de la IA (fortalezas, oportunidades, resumen).', verbose_name='Razones del Análisis IA'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='rechazo_automatico_distancia',
            field=models.BooleanField(default=False, help_text='Indica si la postulación fue rechazada automáticamente por la distancia.'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['estado_ia_analisis'], name='gestionOfer_estado__430380_idx'),
        ),
    ]
